language: haxe

os: linux
dist: trusty

haxe:
  - development
  - stable

install:
  - yes | haxelib install main.hxml
  - yes | haxelib install renderer.hxml
  - haxelib git heaps https://github.com/HeapsIO/heaps.git
  - haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git
  - no | haxelib git led-haxe-api https://github.com/deepnight/led-haxe-api.git
  - haxelib list

script:
  - haxe main.hxml
  - haxe renderer.hxml

notifications:
  email:
    on_success: never
    on_failure: always