name: test-windows

on:
  push:
    branches:
      - master
      - dev*
  pull_request:
    branches:
      - master
      - dev*

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest]
        haxe: [4.1.4]
      fail-fast: true
    runs-on: windows-latest

    steps:
      # Get branch name
      - name: getBranch
        shell: bash
        run: echo "::set-output name=v::${GITHUB_REF#refs/heads/}"
        id: branch

      # Checkout & install haxe
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.4
      - run: haxe -version

      # Install libs
      - run: haxelib git castle https://github.com/ncannasse/castle
      - run: haxelib git heaps https://github.com/HeapsIO/heaps.git
      - run: haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git
      - run: haxelib git electron https://github.com/tong/hxelectron.git
      - run: haxelib git ldtk-haxe-api https://github.com/deepnight/ldtk-haxe-api.git --always

      # Install haxe API (use same branch as LDtk if it exists)
      - name: Check Haxe API branch
        id: checkApiBranch
        run: |
          OUTPUT=$(git ls-remote --heads https://github.com/deepnight/ldtk-haxe-api.git | wc -l) && echo "::set-output name=result::$OUPUT"

      - name: Install branch Haxe API
        if: steps.checkApiBranch.outputs.result == 1
        run: haxelib git ldtk-haxe-api https://github.com/deepnight/ldtk-haxe-api.git ${{ steps.branch.outputs.v }}

      - name: Install master Haxe API
        if: steps.checkApiBranch.outputs.result == 0
        run: haxelib git ldtk-haxe-api https://github.com/deepnight/ldtk-haxe-api.git

      - run: haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git
      - run: haxelib list

      # Node/NPM commands
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: cd app && npm install
      - run: cd app && npm run compile

